analytics_admin/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :visitors, only: [:index, :create, :show]
end

analytics_admin/app/models/request_visitor.rb
class RequestVisitor
  include ActiveModel::Model
  attr_accessor :email, :views, :visitor

  validates :email,
            presence: true
  validates :views,
            presence: true

  def save
    if valid?
      persist!
      true
    else
      false
    end
  end


  private
    def persist!
      @visitor = Visitor.where(email: email).first_or_create
      views.each do |view| 
        next if(view[:id].present? && @visitor.views.exists?(view[:id]))
        @visitor.views.build(view)
      end
      @visitor.save!
    end
end

analytics_admin/app/models/view.rb
class View < ApplicationRecord
  validates :url,
            presence: true
  validates :visited_at,
            presence: true
end

analytics_admin/app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :views
  validates :email,
            presence: true

  def views_by_day
    views.group_by { |view| view.visited_at.to_date }
  end
end

analytics_admin/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @visitor_count = Visitor.count
    @view_count = View.count
  end
end

analytics_admin/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show]
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @visitors = Visitor.all
  end

  def show
  end

  def create
    @req = RequestVisitor.new(visitor_params)
    if @req.save
      render :show, status: :created
    else
      render json: { message: "Não foi possivel registar o visitante." }, status: :unprocessable_entity
    end
  end

  private
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    def visitor_params
      params.permit(:email, views: [:id, :url, :visited_at])
    end
end

analytics_admin/app/helpers/application_helper.rb
module ApplicationHelper
end

analytics_admin/app/helpers/visitors_helper.rb
module VisitorsHelper
  def gravatar(email)
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=55"
  end
end

analytics_admin/app/views/home/index.html.erb
<div class="col-lg-12">
  <h1 class="page-header">Métricas</h1>
</div>
<div class="row">
  <div class="col-xs-12 col-md-5 col-md-offset-2">
    <div class="circle">
      <div class="c100 p100">
        <span id="visitor_count"><%= @visitor_count %></span>
        <div class="slice">
          <div class="bar"></div>
          <div class="fill"></div>
        </div>
      </div>
      <h5 class="title">Visitantes</h5>
    </div>
  </div>
  <div class="col-xs-12 col-md-5" >
    <div class="circle">
      <div class="c100 p100 blue">
        <span id="views_count"><%= @view_count %></span>
        <div class="slice">
          <div class="bar"></div>
          <div class="fill"></div>
        </div>
      </div>
      <h5>Visualizações</h5>
    </div>
  </div>
</div>

analytics_admin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cool Analytics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span>Analytics</span>Admin</a>
          <ul class="nav navbar-nav">
            <li> <%= link_to 'Home', root_path %> </li>
            <li> <%= link_to 'Visitors', visitors_path %> </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= notice %>
      <%= yield %>
    </div>
  </body>
</html>

analytics_admin/app/views/visitors/index.html.erb
<div class="col-lg-12">
  <h1 class="page-header">Visitantes</h1>
</div>
<div class="row">
  <% @visitors.each do |visitor| %>
    <div class="visitor col-xs-12 col-md-5">
      <%= link_to(visitor_path(visitor)) do %>
        <div class="visitor-avatar">
          <img class="media-object" src="<%= gravatar(visitor.email) %>" alt="...">
        </div>
        <div class="visitor-name">
          <h4><%= visitor.email %></h4>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

analytics_admin/app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <img src="<%= gravatar(@visitor.email)%>" />
  <strong>Email:</strong>
  <%= @visitor.email %>
</div>
<hr>
<h4>Paginas Visitadas</h4>
<% @visitor.views_by_day.each do |day, views| %>
  <table class="table">
    <caption><%= day.strftime('%d/%m/%Y') %></caption>
    <thead>
      <tr>
        <th>URL</th>
        <th>Data/Hora</th>
      </tr>
    </thead>
    <tbody>
      <% views.each do |v| %>
        <tr>
          <td><%= link_to v.url, v.url, target: '_blank' %></td>
          <td><%= v.visited_at.to_s(:view) %></td>
        </tr> 
      <% end %>    
    </tbody>
  </table>
<% end %>